spring:
    profiles:
        activate:dev
    
---
spring:
    profiles:dev
    applicaiton:
        name: springcloud-config-dev
---
spring:
    profiles:test
    applicaiton:
        name: springcloud-config-test