spring:
  profiles: 
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.tf1997.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql//localhost:3306/db01?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka默认描述信息
    prefer-ip-address: true #显示服务的ip

# info配置
info:
  app.name: tf1997-springcloud
  company.name: com.tf1997
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.tf1997.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql//localhost:3306/db01?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka默认描述信息
    prefer-ip-address: true #显示服务的ip

# info配置
info:
  app.name: tf1997-springcloud
  company.name: com.tf1997